language: go
go_import_path: googlemaps.github.io/maps

# See https://github.com/travis-ci/gimme/blob/master/.testdata/binary-linux for known golang versions
go:
  - "1.7"
  - "1.8"
  - "1.9"
  - "1.10"
  - "1.11"
  - tip

# These are failing due to missing deps. 
# script: 
#   - go list -f '{{if len .TestGoFiles}}"go test -v -covermode=atomic -coverprofile={{.Dir}}/coverage.txt {{.ImportPath}}"{{end}}' ./... | xargs sh -c
#   - go tool cover -func=coverage.txt
